name: preference_helper
description: A package that makes shared_preferences easier to use, This package is built with bloc, shared_preferences
version: 0.0.5+1
author: Namhyun, Gu <mnhan0403@gmail.com>
homepage: https://github.com/namhyun-gu/preference-helper

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.1+1
  bloc: ^0.9.5
  flutter_bloc: ^0.7.1
  equatable: ^0.2.3
  meta: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
